# Stage 1: Build Next.js Static Export
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: Serve via Nginx
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Next.js static output folder '/out' se Nginx html path me copy karein
COPY --from=build /app/out /usr/share/nginx/html

EXPOSE 100

CMD ["nginx", "-g", "daemon off;"]
